name: Windows RDP (ngrok)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:

      - name: Enable RDP
        run: |
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Download ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip

      - name: Auth ngrok
        run: |
          .\ngrok\ngrok.exe authtoken $env:NGROK_TOKEN
        env:
          NGROK_TOKEN: 313Op1iVe02QTiOykvVrLyjdc2h_2pfAjKKsGv4uwDrXTxf3E

      - name: Start tunnel
        run: |
          Start-Process -NoNewWindow -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389"

      - name: Wait for tunnel
        run: Start-Sleep -Seconds 10

      - name: Keep alive
        run: Start-Sleep -Seconds 21600
